[package]
name = "simple-worker-foundry"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.38.0", features = ["full"] }
lapin = "2"
tokio-executor-trait = "2.1.1"
tokio-reactor-trait = "1.1.0"
